---
title: "Assignment_1_Krzywicki"
format: html
---

1) How does geographic analysis fit into your goals for your research? Given our discussion of the aims and limitations of geographic analysis, are there particular issues that you would like to know more about or guard against?

I am hoping to describe the relationship between land use change along migratory networks and changes to sense of place at other locations along that network.If that goes well maybe their will be some explanation and inference afterwards. I need to be worried about the atomic and ecological fallacies, as well as being very clear about scale.  

2) What are the primary components that describe spatial data?

Some of the primary components describing spatial data are cooridinates, cooridinate reference system, geometry, scale and resolution. 

3) What is the coordinate reference system and why is it important

The coordinate reference system describes the different types of information that inform a map's projection. It includes thing like the datum, ellipsoid, units, and other types of information. Not every CRS uses all these different parameters. 

5) Find two maps of the same area in different projections? How does the projection affect your perception of the data being displayed?

maps source: https://futuremaps.com/blogs/news/top-10-world-map-projections?srsltid=AfmBOortA7V05EZPMLMu_VQU0zUVexfKDp2VH6_dzUMqBhKnlold902y

Robinson projection: according to the source, Robinson played around until things looked nice, following a trial and error method til they were happy. Has some of the issues of a mercator projection but less dramatic. 

Dymaxion Map: Created by Buckminster Fuller. Projected earth onto a icosahedron, which allowed a 3d model of the earth to be flattened out in 2-dimensional space. Most striking thing about this map is how it points out the variety of compromises map makers go through to project the globe onto a 2D space. 

6) Read in the cejst.shp file in the assignment01 folder. How many attributes describe each object? How many unique geometries are there? What is the coordinate reference system?

Attributes describing each object?
Unique geometries: 18


```{r}
library(sf)
cejst <- read_sf(dsn = "/opt/data/data/assignment01/cejst_nw.shp")


geometry_types <- st_geometry_type(cejst)
unique_geometries <- unique(geometry_types)
print("Unique geometries:")
print(unique_geometries)

num_attributes <- ncol(cejst)
print(paste("Number of attributes:", num_attributes))
```

